### ISSUE TITLE
Why are the only ten splits provided?

### ISSUE THREAD

**Issue by hooraid** [naraysa/gzsl-od#2]
In the paper, experiments were conducted on the 30 random splits but provided splits are only ten.

Why are the only ten splits provided?

**Comment by naraysa** [comment]
30 random splits have been shared. However, these are newly created splits, as we do not have the splits that were used in the paper.

**Comment by Xjunjiang** [comment]
> 30 random splits have been shared. However, these are newly created splits, as we do not have the splits that were used in the paper.

hello，

> 30 random splits have been shared. However, these are newly created splits, as we do not have the splits that were used in the paper.

Hello,Thank you very much for your work！Can you tell us where we can download 30 random splits?

**Comment by naraysa** [comment]
The link is shared in the README.md of this repo.
