### ISSUE TITLE
Curious about division of seen and unseen categories of actions.

### ISSUE THREAD

**Issue by GayatriPurandharT** [naraysa/gzsl-od#5]
Hello, I would like to know the division of the type of actions you considered for seen and the actions under unseen categories to produce the results mentioned in the paper on both HMDB51 and UCF101 datasets. Will the choice of actions under the seen and unseen category affect the result? 
Please give some insight on this
Thank you.

**Comment by naraysa** [comment]
As mentioned in the paper, we use random splitting of classes and average the performance on 30 different splits.
